version: '3.8'

services:
  # Serviço 1: Prometheus (O Banco de Dados de Métricas)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    # Monta o arquivo de configuração que vamos criar
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # Serviço 2: Node Exporter (O Agente na VPS)
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    # network_mode: 'host' e 'pid: "host"' são cruciais
    # para ele ler as métricas da VPS (host) e não do container
    network_mode: 'host'
    pid: "host"
    ports:
      - '9100:9100'

  # Serviço 3: Grafana (O Dashboard Visual)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    # Cria um volume para persistir seus dashboards
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
